const SELECT_INDEX = 0;
const PROJECTIONS_INDEX = 1;
const FROM_INDEX = 2;
const COLLECTION_INDEX = 3;
const OPTIONAL_ARGUMENT_INDEX = 4;
const OPTIONAL_CONDITION_INDEX = 5;

module.exports = { 
  SELECT_INDEX,
  PROJECTIONS_INDEX,
  FROM_INDEX,
  COLLECTION_INDEX,
  OPTIONAL_ARGUMENT_INDEX,
  OPTIONAL_CONDITION_INDEX
}